stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - pytest --cov=.
  coverage: '/TOTAL.*\s+(\d+%)$/'

lint:
  stage: test
  image: python:3.12
  script:
    - pip install flake8 black
    - flake8 .
    - black --check .

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy-staging:
  stage: deploy
  script:
    - helm upgrade --install schema-platform ./helm
  environment:
    name: staging
  only:
    - develop
